services:
  php72:
    build:
      context: .
      dockerfile: Dockerfile72
    container_name: php72
    volumes:
      - ./:/var/www/html

  php80:
    build:
      context: .
      dockerfile: Dockerfile80
    container_name: php80
    volumes:
      - ./:/var/www/html
