version: '3.7'
services:
  wead-cep-gratis:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    networks:
      - wead_cep_gratis
    volumes:
      - './:/var/www/html'
networks:
  wead_cep_gratis: null
